theme: jekyll-theme-minimal

title: Tahir Raza's Journal
tagline: [Software Engineer | Learner | Raconteur | Avid Traveller | Father]
description: [Software Engineer | Learner | Raconteur | Avid Traveller | Father]
author: Tahir Raza

email: tahirraza.se@gmail.com
phone: +92-306-678-1409

linkedinurl: https://pk.linkedin.com/in/tahir-raza-38a75596
githurl: https://github.com/alyjee
twitterurl: https://twitter.com/tahirraza_se
stackoverflowurl: https://stackoverflow.com/users/5436736/tahir-raza

google_analytics: UA-144488030-1

plugins:
  - jekyll-seo-tag